//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dogmaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogdetail
    {
        public int id { get; set; }
        public string notes { get; set; }
        public int completedProgramsID { get; set; }
        public int enrolledProgramsID { get; set; }
        public string intakeForms { get; set; }
    }
}
