//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dogmaAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dogmaEntities : DbContext
    {
        public dogmaEntities()
            : base("name=dogmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dog> dogs { get; set; }
        public virtual DbSet<dogdetail> dogdetails { get; set; }
        public virtual DbSet<dogsummary> dogsummaries { get; set; }
        public virtual DbSet<dogtag> dogtags { get; set; }
        public virtual DbSet<enrolledprogram> enrolledprograms { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<memberdog> memberdogs { get; set; }
        public virtual DbSet<programsdetail> programsdetails { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<trainingprogram> trainingprograms { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vaccination> vaccinations { get; set; }
    }
}
