//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dogmaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberdog
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string colors { get; set; }
        public string breed { get; set; }
        public string gender { get; set; }
        public string image { get; set; }
        public int ownersId { get; set; }
        public int tagId { get; set; }
    }
}
