//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dogmaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingprogram
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string image { get; set; }
        public int lowerAgeLimit { get; set; }
        public int upperAgeLimit { get; set; }
        public int preRequisiteID { get; set; }
        public int scheduleID { get; set; }
        public string webinarLink { get; set; }
        public string notes { get; set; }
        public bool allowRecurring { get; set; }
        public bool archived { get; set; }
        public int membershipID { get; set; }
        public int capacity { get; set; }
    }
}
