//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dogmaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int id { get; set; }
        public int dogsID { get; set; }
        public string emergencyContact { get; set; }
        public string emergencyContactPhone { get; set; }
    }
}
